name: deploy_ios

on:
  workflow_dispatch:

jobs:
  release-archive:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode 26.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0"

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: .derivedData
          key: ${{ runner.os }}-derived-${{ hashFiles('MaTool.xcodeproj/project.pbxproj', '**/*.swift', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-derived-

      - name: Build
        run: |
          xcodebuild archive \
            -workspace App/MaTool.xcodeproj \
            -scheme MaTool \
            -archivePath App/MaTool.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .derivedData \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_SWIFT_MACROS=YES

      - name: Create ExportOptions.plist
        run: |
          echo '${{ secrets.EXPORT_OPTIONS }}' > ExportOptions.plist
          cat ExportOptions.plist

      - name: Create Private Key
        run: |
          mkdir private_keys
          echo -n '${{ secrets.APPLE_API_KEY_BASE64 }}' | base64 --decode > ./private_keys/AuthKey_${{ secrets.APPLE_API_ISSUE_ID }}.p8

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath MaTool.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath MaTool.ipa -allowProvisioningUpdates -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.APPLE_API_ISSUE_ID }}.p8 -authenticationKeyID ${{ secrets.APPLE_API_KEY_ID }} -authenticationKeyIssuerID ${{ secrets.APPLE_API_ISSUE_ID }}

      - name: Upload to App Store Connect
        run: |
          xcrun altool --upload-app -f MaTool.ipa/MaTool.ipa -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APP_SPECIFIC_PASSWORD }} --type ios
