name: Prod iOS Dispatch
on:
  push:
    branches:
      - 'release-ios'
jobs:
    deploy_iosapp:
        name: Deploy iOS App
        uses: ./.github/workflows/jobs/deploy_iosapp.yml
        secrets: inherit