name: Prod iOS Dispatch
on:
  push:
    branches:
      - 'release-ios'
      - 'feature/ci-v2'
jobs:
    deploy_iosapp:
        name: Deploy iOS App
        uses: ./.github/workflows/job_deploy_iosapp.yml
        secrets: inherit