name: Deploy iOS App

on:
  workflow_call:

jobs:
  release-archive:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode 26.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0"

      - name: Ensure SPM Cache Dir Exists
        run: mkdir -p ~/Library/Caches/org.swift.swiftpm

      - name: Restore SPM Cache
        id: cache-spm-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm/
          key: ${{ runner.os }}-xcode26-spm-iosapp-${{ hashFiles('iOSApp/Package.resolved', 'Shared/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode26-spm-iosapp-

      - name: Build
        run: |
          xcodebuild archive \
            -project iOSApp/MaTool.xcodeproj \
            -scheme iOSApp \
            -archivePath iOSApp/MaTool.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath iOSApp/.derivedData \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_SWIFT_MACROS=YES

      - name: Create ExportOptions.plist
        run: |
          echo '${{ secrets.EXPORT_OPTIONS }}' > ExportOptions.plist
          cat ExportOptions.plist

      - name: Create Private Key
        run: |
          mkdir private_keys
          echo -n '${{ secrets.APPLE_API_KEY_BASE64 }}' | base64 --decode > ./private_keys/AuthKey_${{ secrets.APPLE_API_ISSUE_ID }}.p8

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath iOSApp/MaTool.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/export -allowProvisioningUpdates -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.APPLE_API_ISSUE_ID }}.p8 -authenticationKeyID ${{ secrets.APPLE_API_KEY_ID }} -authenticationKeyIssuerID ${{ secrets.APPLE_API_ISSUE_ID }}

      - name: Upload to App Store Connect
        run: |
          xcrun altool --upload-app -f build/export/MaTool.ipa -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APP_SPECIFIC_PASSWORD }} --type ios

      - name: Save SPM Cache
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-'))
        uses: actions/cache/save@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm/
          key: ${{ steps.cache-spm-restore.outputs.cache-primary-key }}
